// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowCase.Data;

namespace ShowCase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ShowCase.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 1",
                            Price = 65.859999999999999
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 2",
                            Price = 12.51
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 3",
                            Price = 55.57
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 4",
                            Price = 86.180000000000007
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 5",
                            Price = 52.549999999999997
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 6",
                            Price = 85.310000000000002
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 7",
                            Price = 41.640000000000001
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 8",
                            Price = 35.950000000000003
                        },
                        new
                        {
                            Id = 9,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 9",
                            Price = 45.200000000000003
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 10",
                            Price = 79.109999999999999
                        },
                        new
                        {
                            Id = 11,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 11",
                            Price = 58.57
                        },
                        new
                        {
                            Id = 12,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 2",
                            Price = 82.170000000000002
                        },
                        new
                        {
                            Id = 13,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 13",
                            Price = 12.56
                        },
                        new
                        {
                            Id = 14,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 14",
                            Price = 70.980000000000004
                        },
                        new
                        {
                            Id = 15,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 15",
                            Price = 30.170000000000002
                        },
                        new
                        {
                            Id = 16,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 16",
                            Price = 64.319999999999993
                        },
                        new
                        {
                            Id = 17,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 17",
                            Price = 17.629999999999999
                        },
                        new
                        {
                            Id = 18,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 18",
                            Price = 55.649999999999999
                        },
                        new
                        {
                            Id = 19,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 19",
                            Price = 13.5
                        },
                        new
                        {
                            Id = 20,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 20",
                            Price = 32.740000000000002
                        },
                        new
                        {
                            Id = 21,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 21",
                            Price = 35.100000000000001
                        },
                        new
                        {
                            Id = 22,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 22",
                            Price = 62.810000000000002
                        },
                        new
                        {
                            Id = 23,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 23",
                            Price = 50.829999999999998
                        },
                        new
                        {
                            Id = 24,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 24",
                            Price = 47.600000000000001
                        },
                        new
                        {
                            Id = 25,
                            Description = "Lorem Ipsum is simply dummy text",
                            Name = "Item 25",
                            Price = 14.59
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
